### ISSUE TITLE
torch 1.12.1

### ISSUE THREAD

**Issue by doublex** [IIGROUP/MANIQA#15]
Running `inference.py` after upgrading to `pytorch 1.12.1`:

````
Traceback (most recent call last):
  File "convert-video.py", line 33, in <module>
    maniqa_scores = MANIQA.from_files([
  File "/home/max/MANIQA/__init__.py", line 53, in from_files
    pred += net(x_d)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/max/MANIQA/models/maniqa.py", line 121, in forward
    _x = self.vit(x)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/max/MANIQA/models/timm/models/vision_transformer.py", line 407, in forward
    x = self.forward_features(x)
  File "/home/max/MANIQA/models/timm/models/vision_transformer.py", line 398, in forward_features
    x = self.blocks(x)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/max/MANIQA/models/timm/models/vision_transformer.py", line 273, in forward
    x = x + self.drop_path(self.mlp(self.norm2(x)))
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/max/MANIQA/models/timm/models/layers/mlp.py", line 27, in forward
    x = self.act(x)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 681, in forward
    return F.gelu(input, approximate=self.approximate)
  File "/home/max/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GELU' object has no attribute 'approximate'
````

**Comment by Ellyuca** [comment]
Hi @doublex . Did you mange to solve this issue?
I am having the same problem...

Thanks.

**Comment by doublex** [comment]
@Ellyuca 
Not so far. Do you have an idea?

**Comment by Ellyuca** [comment]
Hi @doublex .
I just manged to make the `inference.py` code run.
I was trying it on google colab, where the pytorch version is 1.12.

So I did this:
```
!pip uninstall torch
!pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

```

I still have to understand a few things about the `inference.py` code, but at least for now it runs.
Hope it helps.

**Comment by doublex** [comment]
@Ellyuca 
Thanks for answer. I can't downgrade torch...

**Comment by Ellyuca** [comment]
@doublex 
Have you tried what is suggested here https://github.com/facebookresearch/fairseq/issues/2510 ?

**Comment by doublex** [comment]
You are right - monkey-patching GELU from torch 1.11 works:

````python
class GELU(torch.nn.Module):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.nn.functional.gelu(input)
torch.nn.modules.activation.GELU = GELU
````

**Comment by Ellyuca** [comment]
Hi, @doublex. I will also have to do something like these, since for a specific task I won't be able to downgrade the torch version.
Could you please share the exact modifications you have made to the code?
I would really appreciate it.
Thanks.

**Comment by doublex** [comment]
As written before:

````python
import torch
class GELU(torch.nn.Module):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.nn.functional.gelu(input)
torch.nn.modules.activation.GELU = GELU
````

**Comment by Ellyuca** [comment]
Oh yeah, sorry. I completely missed that part.
Thanks!!

**Comment by doublex** [comment]
Pleasure to work with you

**Comment by TianheWu** [comment]
Thanks for answering! @Ellyuca @doublex
